site_name: PythonMini Documentation
theme: readthedocs
docs_dir: 'doc'
pages:
    - 'Home': 'index.md'
    - 'Core':
        - 'Number': 'core/number.md'
        - 'Boolean': 'core/boolean.md'
        - 'Comparison': 'core/comparison.md'
        - 'None': 'core/none.md'
        - 'String': 'core/string.md'
        - 'Function': 'core/function.md'
    - 'Standard Modules':
        - 'collections': 'stdmod/collections.md'
        - 'json': 'stdmod/json.md'
        - 'math': 'stdmod/math.md'
        - 'operator': 'stdmod/operator.md'
        - 'random': 'stdmod/random.md'
        - 're': 'stdmod/regexp.md'
        - 'string': 'stdmod/string.md'
        - 'time': 'stdmod/time.md'
    - 'Turtle Graphic':
        - 'turtle': 'turtle/turtle.md'
    - 'Processing Graphic':
        - 'setup': 'processing/setup.md'
        - 'keyboard': 'processing/keyboard.md'
        - 'mouse': 'processing/mouse.md'
extra_css:
    - css/doc.css
