site_name: Python Mini Document
theme: readthedocs
docs_dir: 'doc'
pages:
    - 'Home': 'index.md'
    - 'Core':
        - 'Types': 'core/types.md'
    - 'Standard Modules':
        - 'math': 'stdmod/math.md'
        - 'random': 'stdmod/random.md'
        - 'time': 'stdmod/time.md'
        - 're': 'stdmod/regexp.md'
    - 'Turtle Graphic':
        - 'turtle': 'turtle/turtle.md'
    - 'Processing Graphic':
        - 'setup': 'processing/setup.md'
        - 'keyboard': 'processing/keyboard.md'
        - 'mouse': 'processing/mouse.md'
extra_css:
    - css/doc.css
