site_name: Python Mini Document
theme: readthedocs
docs_dir: 'doc'
pages:
    - 'Home': 'index.md'
    - 'Core':
        - 'Types': 'core/types.md'
    - 'Standard Modules':
        - 'Math': 'stdmod/math.md'
        - 'Random': 'stdmod/random.md'
        - 'Time': 'stdmod/time.md'
    - 'Turtle Graphic':
        - 'Motion': 'turtle/motion.md'
    - 'Processing Graphic':
        - 'Setup': 'processing/setup.md'
        - 'Keyboard': 'processing/keyboard.md'
        - 'Mouse': 'processing/mouse.md'
extra_css:
    - css/doc.css
